Repository travis-ci/travis-build, pull requests merged in 2018-10, with the labels that each got.

#1496 Add Windows support
  lib/travis/build/appliances/base.rb
  lib/travis/build/appliances/checkout.rb
  lib/travis/build/appliances/disable_sudo.rb
  lib/travis/build/appliances/env.rb
  lib/travis/build/appliances/etc_hosts_pinning.rb
  lib/travis/build/appliances/fix_etc_hosts.rb
  lib/travis/build/appliances/fix_resolv_conf.rb
  lib/travis/build/appliances/fix_sudo_enabled_trusty.rb
  lib/travis/build/appliances/services.rb
  lib/travis/build/appliances/update_glibc.rb
  lib/travis/build/appliances/update_libssl.rb
  lib/travis/build/appliances/validate.rb
  lib/travis/build/bash/travis_setup_env.bash
  lib/travis/build/bash/travis_temporary_hacks.bash
  lib/travis/build/bash/travis_terminate.bash
Labels: enhancement, wip

#1511 Add integration specs for travis_retry
  .travis.yml
  Gemfile
  Gemfile.lock
  Rakefile
  lib/travis/build/rake_tasks.rb
  script/assert-examples
  spec/build/bash/travis_retry_spec.rb
Labels: awaiting-review

#1515 Replace assert-examples script with specs
  .travis.yml
  lib/travis/build/rake_tasks.rb
  script/assert-examples
  spec/build/rake_tasks_spec.rb
  spec/build/script/android_spec.rb
  spec/build/script/c_spec.rb
  spec/build/script/clojure_spec.rb
  spec/build/script/cpp_spec.rb
  spec/build/script/crystal_spec.rb
  spec/build/script/csharp_spec.rb
  spec/build/script/d_spec.rb
  spec/build/script/dart_spec.rb
  spec/build/script/elixir_spec.rb
  spec/build/script/erlang_spec.rb
  spec/build/script/go_spec.rb
  spec/build/script/groovy_spec.rb
  spec/build/script/haskell_spec.rb
  spec/build/script/haxe_spec.rb
  spec/build/script/header_spec.rb
  spec/build/script/julia_spec.rb
  spec/build/script/nix_spec.rb
  spec/build/script/node_js_spec.rb
  spec/build/script/objective_c_spec.rb
  spec/build/script/perl6_spec.rb
  spec/build/script/perl_spec.rb
  spec/build/script/php_spec.rb
  spec/build/script/pure_java_spec.rb
  spec/build/script/python_spec.rb
  spec/build/script/r_spec.rb
  spec/build/script/ruby_spec.rb
  spec/build/script/rust_spec.rb
  spec/build/script/scala_spec.rb
  spec/build/script/shared/bash_script.rb
  spec/build/script/smalltalk_spec.rb
  spec/spec_helper.rb
  spec/spec_helpers/bash_script.rb
  spec/spec_helpers/sexp.rb
  spec/support/payloads.rb
Labels: awaiting-review

#1529 Add integration spec for travis_preamble func
  lib/travis/build/bash/travis_preamble.bash
  spec/build/bash/travis_preamble_spec.rb
  spec/build/bash/travis_retry_spec.rb
  spec/spec_helpers/bash_function.rb
Labels: awaiting-review

#1531 Add specs for travis_setup_env bash func
  lib/travis/build/bash/travis_setup_env.bash
  spec/build/bash/travis_setup_env_spec.rb
Labels: awaiting-review

#1528 Handle case where trace name first line is nil
  lib/travis/shell/generator/bash.rb
Labels: awaiting-review

#1535 Remove unused encrypted docker config tarball
  .docker.tar.bz2.enc
Labels: awaiting-review

#1536 Add spec for travis_whereami
  spec/build/bash/travis_whereami_spec.rb
Labels: awaiting-review

#1537 Begin selectively rubocopping
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
  Rakefile
  config.ru
  lib/travis/build/rake_tasks.rb
  script/build-s3-index-html
  script/compile
Labels: awaiting-review

#1549 Bump to ruby 2.5.3
  .ruby-version
  .travis.yml
  Dockerfile
Labels: awaiting-review

#1015 Relax branch names when computing cache names
  lib/travis/build/script/shared/directory_cache/base.rb
  spec/build/script/directory_cache/gcs_spec.rb
  spec/build/script/directory_cache/s3_spec.rb
  spec/build/script/directory_cache_spec.rb
Labels: awaiting-review, bug
