Repository travis-ci/travis-build, pull requests merged in 2018-12, with the labels that each got.

#1609 Remove the bogus APT https proxy config value of "false"
  lib/travis/build/bash/travis_setup_apt_proxy.bash
  spec/build/script/shared/bash_script.rb
Labels: awaiting-review

#1612 Add back explicit APT https proxy disabling
  lib/travis/build/bash/travis_setup_apt_proxy.bash
Labels: awaiting-review

#1601 C#: Shellescape solution name
  lib/travis/build/script/csharp.rb
  spec/build/script/csharp_spec.rb
Labels: community

#1583 Build with scala 2.12.7
  lib/travis/build/script/scala.rb
  spec/build/script/scala_spec.rb
Labels: lang-scala

#1625 Update URL for docker image language mapping
  spec/spec_helpers/bash_script.rb
Labels: awaiting-review
