Repository travis-ci/travis-build, pull requests merged in 2018-11, with the labels that each got.

#1562 Slim down the docker image
  Dockerfile
  script/server
Labels: awaiting-review

#1546 Add more rubocop coverage
  .rubocop.yml
  lib/core_ext/hash/compact.rb
  lib/core_ext/hash/deep_merge.rb
  lib/core_ext/hash/deep_symbolize_keys.rb
  lib/core_ext/object/false.rb
  lib/core_ext/string/indent.rb
  lib/core_ext/string/output_safe.rb
  lib/core_ext/string/to_bool.rb
  lib/core_ext/string/unindent.rb
  lib/travis/build/rake_tasks.rb
Labels: awaiting-review

#1567 Further cleanups of docker image
  .dockerignore
  Dockerfile
  lib/travis/build.rb
  script/healthcheck
  script/server
Labels: awaiting-review

#1168 Suppress new version warning for CocoaPods
  lib/travis/build/script/objective_c.rb
  spec/build/script/objective_c_spec.rb
Labels: lang-objc

#1593 Be more defensive when checking for shellcheck presence
  lib/travis/build/rake_tasks.rb
Labels: awaiting-review

#1592 Switch to http for hhvm (#1589)
  lib/travis/build/appliances/fix_hhvm_source.rb
Labels: enterprise-2.2-backport

#1597 Ensure a valid GITHUB_OAUTH_TOKEN value is set
  script/validate-example-payloads-with-docker
Labels: awaiting-review

#1596 Clarifying/expanding documentation in README.
  README.md
Labels: documentation

#1598 Add bash+ruby func for ipv4 DNS lookups
  lib/travis/build/bash/travis_getaddrinfo.bash
  spec/build/bash/travis_getaddrinfo_spec.rb
  spec/spec_helpers/bash_function.rb
Labels: awaiting-review

#934 Add Elm language support
  lib/travis/build/addons/deploy/script.rb
  lib/travis/build/script.rb
  lib/travis/build/script/elm.rb
  spec/build/script/elm_spec.rb
Labels: community, enhancement

#1606 Add APT proxy when available and healthy
  lib/travis/build/appliances/apt_get_update.rb
  lib/travis/build/bash/travis_munge_apt_sources.bash
  lib/travis/build/bash/travis_setup_apt_proxy.bash
  lib/travis/build/config.rb
  lib/travis/build/script.rb
Labels: awaiting-review
