Repository travis-ci/travis-build, pull requests merged in 2019-07, with the labels that each got.

#1728 Handle arch specification in Julia script
  lib/travis/build/script/julia.rb
Labels: lang-julia

#1739 Bump R release to 3.6.1
  lib/travis/build/script/r.rb
  spec/build/script/r_spec.rb
Labels: lang-r

#1751 Fix URL for downloading R-devel on macOS
  lib/travis/build/script/r.rb
  spec/build/script/r_spec.rb
Labels: community, lang-r
